//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGioHang
    {
        public int IDDonHangMua { get; set; }
        public int MaSanPham { get; set; }
        public int SoLuong { get; set; }
        public double ThanhTien { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
        public virtual GioHang_DonHangMua GioHang_DonHangMua { get; set; }
    }
}
