//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int IDDanhGia { get; set; }
        public int IDUserMua { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
        public int DiemDanhGia { get; set; }
        public int MaSanPham { get; set; }
    }
}
