//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThai_DonHangMua
    {
        public TrangThai_DonHangMua()
        {
            this.GioHang_DonHangMua = new HashSet<GioHang_DonHangMua>();
        }
    
        public int IDTrangThai { get; set; }
        public string TenTrangThai { get; set; }
    
        public virtual ICollection<GioHang_DonHangMua> GioHang_DonHangMua { get; set; }
    }
}
