//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDang
    {
        public BaiDang()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int MaSanPham { get; set; }
        public int MaLoai { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public int GiaSP { get; set; }
        public int SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public System.DateTime NgayDang { get; set; }
        public int IDTrangThai { get; set; }
        public int Soluongton { get; set; }
        public double DanhGia { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TrangThaiBaiDang TrangThaiBaiDang { get; set; }
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
    }
}
