//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang_DonHangMua
    {
        public GioHang_DonHangMua()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int IDDonHangMua { get; set; }
        public int IDUserMua { get; set; }
        public double TongTien { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int IDTrangThai { get; set; }
    
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual TrangThai_DonHangMua TrangThai_DonHangMua { get; set; }
        public virtual User User { get; set; }
    }
}
