//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HTTT_DoanhNghiepEntities : DbContext
    {
        public HTTT_DoanhNghiepEntities()
            : base("name=HTTT_DoanhNghiepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDang> BaiDangs { get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DbSet<GioHang_DonHangMua> GioHang_DonHangMua { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<TrangThai_DonHangMua> TrangThai_DonHangMua { get; set; }
        public virtual DbSet<TrangThaiBaiDang> TrangThaiBaiDangs { get; set; }
        public virtual DbSet<TrangThaiUser> TrangThaiUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
