//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiUser
    {
        public TrangThaiUser()
        {
            this.Users = new HashSet<User>();
        }
    
        public int IDTrangThaiUser { get; set; }
        public string TenTrangThaiUser { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
